---
title: "Applied Microeconometrics - Assignment 1"
author: "Walter Verwer & Bas Machielsen"
date: "8/31/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. Explain why first differencing the equation does not solve the endogeneity problem of lagged consumption.

First difference estimation is just OLS estimation with transformed data. For the OLS estimator (in general) to be consistent, we need $\text{Cov}(X, U)=0$. In the context of our transformed data, we need $\text{Cov}{\Delta X, \Delta U}=0$. One of the variables in $\Delta X$ is $\Delta Y_{it-1}$. If we evaluate the covariance between $\Delta Y_{it-1}$ and $\Delta U_{it}$, we find that:

\begin{align*}
&\text{Cov}(\Delta Y_{it-1}, \Delta U_{it}) = \\
&\text{Cov}(\beta \Delta X_{it-1} + \rho \Delta Y_{it-2} + \Delta U_{it-1}, \Delta U_{it}) = \\
&\text{Cov}(\Delta U_{it-1}, \Delta U_{it}) \neq 0
\end{align*}

2. Anderson & Hsiao propose a specific instrumental variable procedure for the model. Write down and perform the associated first stage regression. Comment on its outcomes.

The first-stage model is: 

\begin{align*}
C_{it} - C_{it-1} = \beta_0 + \beta_1 \cdot (\log p_{it} - \log p_{it-1}) + \beta_2 \cdot (\log inc_{it} - \log inc_{it-1}) + \\
\beta_3 \cdot (\log ilop_{it} - \log ilop_{it-1}) + \beta_4 \cdot (\log z_{it} - \log z_{it-1}) + u_{it} - u_{it-1}
\end{align*}

Using the data, we find the following first-stage regression:

3. Estimate the specification above using the Anderson & Hsiao approach. Comment on the underlying assumptions, tabulate the results and comment on the outcomes.

4. Describe the Arellano & Bond GMM estimator for this model.

5.Estimate the model parameters using the Arellano & Bond estimator, tabulate the results and discuss the parameter estimates.

6. What is in your estimate for the short-run and the long-run price elasticity of opium?

7. Now estimate the model parameters using the system estimator (Blundell & Bond). Tabulate results, compute the elasticities (as in 6.).

8. Which parameter estimates do you prefer? Explain why. Are there remain- ing problems with your preferred estimates?
